// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: cosigner_service/shamir.proto

package shamirService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nonce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceID      int32  `protobuf:"varint,1,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	DestinationID int32  `protobuf:"varint,2,opt,name=destinationID,proto3" json:"destinationID,omitempty"`
	PubKey        []byte `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Share         []byte `protobuf:"bytes,4,opt,name=share,proto3" json:"share,omitempty"`
	Signature     []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Nonce) Reset() {
	*x = Nonce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosigner_service_shamir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nonce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nonce) ProtoMessage() {}

func (x *Nonce) ProtoReflect() protoreflect.Message {
	mi := &file_cosigner_service_shamir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nonce.ProtoReflect.Descriptor instead.
func (*Nonce) Descriptor() ([]byte, []int) {
	return file_cosigner_service_shamir_proto_rawDescGZIP(), []int{0}
}

func (x *Nonce) GetSourceID() int32 {
	if x != nil {
		return x.SourceID
	}
	return 0
}

func (x *Nonce) GetDestinationID() int32 {
	if x != nil {
		return x.DestinationID
	}
	return 0
}

func (x *Nonce) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *Nonce) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *Nonce) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HRST struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round     int64 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Step      int32 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HRST) Reset() {
	*x = HRST{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosigner_service_shamir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HRST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HRST) ProtoMessage() {}

func (x *HRST) ProtoReflect() protoreflect.Message {
	mi := &file_cosigner_service_shamir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HRST.ProtoReflect.Descriptor instead.
func (*HRST) Descriptor() ([]byte, []int) {
	return file_cosigner_service_shamir_proto_rawDescGZIP(), []int{1}
}

func (x *HRST) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HRST) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *HRST) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *HRST) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CosignerGRPCSetNoncesAndSignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonces    []*Nonce `protobuf:"bytes,1,rep,name=nonces,proto3" json:"nonces,omitempty"`
	Hrst      *HRST    `protobuf:"bytes,2,opt,name=hrst,proto3" json:"hrst,omitempty"`
	SignBytes []byte   `protobuf:"bytes,3,opt,name=signBytes,proto3" json:"signBytes,omitempty"`
	ChainID   string   `protobuf:"bytes,4,opt,name=chainID,proto3" json:"chainID,omitempty"`
}

func (x *CosignerGRPCSetNoncesAndSignRequest) Reset() {
	*x = CosignerGRPCSetNoncesAndSignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosigner_service_shamir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCSetNoncesAndSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCSetNoncesAndSignRequest) ProtoMessage() {}

func (x *CosignerGRPCSetNoncesAndSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosigner_service_shamir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCSetNoncesAndSignRequest.ProtoReflect.Descriptor instead.
func (*CosignerGRPCSetNoncesAndSignRequest) Descriptor() ([]byte, []int) {
	return file_cosigner_service_shamir_proto_rawDescGZIP(), []int{2}
}

func (x *CosignerGRPCSetNoncesAndSignRequest) GetNonces() []*Nonce {
	if x != nil {
		return x.Nonces
	}
	return nil
}

func (x *CosignerGRPCSetNoncesAndSignRequest) GetHrst() *HRST {
	if x != nil {
		return x.Hrst
	}
	return nil
}

func (x *CosignerGRPCSetNoncesAndSignRequest) GetSignBytes() []byte {
	if x != nil {
		return x.SignBytes
	}
	return nil
}

func (x *CosignerGRPCSetNoncesAndSignRequest) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

type CosignerGRPCSetNoncesAndSignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoncePublic []byte `protobuf:"bytes,1,opt,name=noncePublic,proto3" json:"noncePublic,omitempty"`
	Timestamp   int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature   []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *CosignerGRPCSetNoncesAndSignResponse) Reset() {
	*x = CosignerGRPCSetNoncesAndSignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosigner_service_shamir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCSetNoncesAndSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCSetNoncesAndSignResponse) ProtoMessage() {}

func (x *CosignerGRPCSetNoncesAndSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosigner_service_shamir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCSetNoncesAndSignResponse.ProtoReflect.Descriptor instead.
func (*CosignerGRPCSetNoncesAndSignResponse) Descriptor() ([]byte, []int) {
	return file_cosigner_service_shamir_proto_rawDescGZIP(), []int{3}
}

func (x *CosignerGRPCSetNoncesAndSignResponse) GetNoncePublic() []byte {
	if x != nil {
		return x.NoncePublic
	}
	return nil
}

func (x *CosignerGRPCSetNoncesAndSignResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CosignerGRPCSetNoncesAndSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CosignerGRPCGetNoncesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hrst    *HRST  `protobuf:"bytes,1,opt,name=hrst,proto3" json:"hrst,omitempty"`
	ChainID string `protobuf:"bytes,2,opt,name=chainID,proto3" json:"chainID,omitempty"`
}

func (x *CosignerGRPCGetNoncesRequest) Reset() {
	*x = CosignerGRPCGetNoncesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosigner_service_shamir_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCGetNoncesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCGetNoncesRequest) ProtoMessage() {}

func (x *CosignerGRPCGetNoncesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosigner_service_shamir_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCGetNoncesRequest.ProtoReflect.Descriptor instead.
func (*CosignerGRPCGetNoncesRequest) Descriptor() ([]byte, []int) {
	return file_cosigner_service_shamir_proto_rawDescGZIP(), []int{4}
}

func (x *CosignerGRPCGetNoncesRequest) GetHrst() *HRST {
	if x != nil {
		return x.Hrst
	}
	return nil
}

func (x *CosignerGRPCGetNoncesRequest) GetChainID() string {
	if x != nil {
		return x.ChainID
	}
	return ""
}

type CosignerGRPCGetNoncesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonces []*Nonce `protobuf:"bytes,1,rep,name=nonces,proto3" json:"nonces,omitempty"`
}

func (x *CosignerGRPCGetNoncesResponse) Reset() {
	*x = CosignerGRPCGetNoncesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosigner_service_shamir_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosignerGRPCGetNoncesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerGRPCGetNoncesResponse) ProtoMessage() {}

func (x *CosignerGRPCGetNoncesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosigner_service_shamir_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerGRPCGetNoncesResponse.ProtoReflect.Descriptor instead.
func (*CosignerGRPCGetNoncesResponse) Descriptor() ([]byte, []int) {
	return file_cosigner_service_shamir_proto_rawDescGZIP(), []int{5}
}

func (x *CosignerGRPCGetNoncesResponse) GetNonces() []*Nonce {
	if x != nil {
		return x.Nonces
	}
	return nil
}

var File_cosigner_service_shamir_proto protoreflect.FileDescriptor

var file_cosigner_service_shamir_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x95,
	0x01, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x66, 0x0a, 0x04, 0x48, 0x52, 0x53, 0x54, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xb4,
	0x01, 0x0a, 0x23, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53,
	0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x06, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x68, 0x72, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x48, 0x52, 0x53, 0x54, 0x52, 0x04, 0x68, 0x72, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x84, 0x01, 0x0a, 0x24, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x41,
	0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x61, 0x0a, 0x1c,
	0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x4e,
	0x6f, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04,
	0x68, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61,
	0x6d, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x52, 0x53, 0x54, 0x52,
	0x04, 0x68, 0x72, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22,
	0x4d, 0x0a, 0x1d, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x06, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x06, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x32, 0xf8,
	0x01, 0x0a, 0x0d, 0x49, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43,
	0x12, 0x7d, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x6e, 0x64,
	0x53, 0x69, 0x67, 0x6e, 0x12, 0x32, 0x2e, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50,
	0x43, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x53, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x73, 0x68, 0x61, 0x6d, 0x69,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x6e,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x68, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x2b, 0x2e, 0x73,
	0x68, 0x61, 0x6d, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73, 0x68, 0x61, 0x6d,
	0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6c,
	0x6f, 0x76, 0x65, 0x2d, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f, 0x68, 0x6f, 0x72,
	0x63, 0x72, 0x75, 0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x6d, 0x69, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cosigner_service_shamir_proto_rawDescOnce sync.Once
	file_cosigner_service_shamir_proto_rawDescData = file_cosigner_service_shamir_proto_rawDesc
)

func file_cosigner_service_shamir_proto_rawDescGZIP() []byte {
	file_cosigner_service_shamir_proto_rawDescOnce.Do(func() {
		file_cosigner_service_shamir_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosigner_service_shamir_proto_rawDescData)
	})
	return file_cosigner_service_shamir_proto_rawDescData
}

var file_cosigner_service_shamir_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cosigner_service_shamir_proto_goTypes = []interface{}{
	(*Nonce)(nil), // 0: shamirService.Nonce
	(*HRST)(nil),  // 1: shamirService.HRST
	(*CosignerGRPCSetNoncesAndSignRequest)(nil),  // 2: shamirService.CosignerGRPCSetNoncesAndSignRequest
	(*CosignerGRPCSetNoncesAndSignResponse)(nil), // 3: shamirService.CosignerGRPCSetNoncesAndSignResponse
	(*CosignerGRPCGetNoncesRequest)(nil),         // 4: shamirService.CosignerGRPCGetNoncesRequest
	(*CosignerGRPCGetNoncesResponse)(nil),        // 5: shamirService.CosignerGRPCGetNoncesResponse
}
var file_cosigner_service_shamir_proto_depIdxs = []int32{
	0, // 0: shamirService.CosignerGRPCSetNoncesAndSignRequest.nonces:type_name -> shamirService.Nonce
	1, // 1: shamirService.CosignerGRPCSetNoncesAndSignRequest.hrst:type_name -> shamirService.HRST
	1, // 2: shamirService.CosignerGRPCGetNoncesRequest.hrst:type_name -> shamirService.HRST
	0, // 3: shamirService.CosignerGRPCGetNoncesResponse.nonces:type_name -> shamirService.Nonce
	2, // 4: shamirService.ICosignerGRPC.SetNoncesAndSign:input_type -> shamirService.CosignerGRPCSetNoncesAndSignRequest
	4, // 5: shamirService.ICosignerGRPC.GetNonces:input_type -> shamirService.CosignerGRPCGetNoncesRequest
	3, // 6: shamirService.ICosignerGRPC.SetNoncesAndSign:output_type -> shamirService.CosignerGRPCSetNoncesAndSignResponse
	5, // 7: shamirService.ICosignerGRPC.GetNonces:output_type -> shamirService.CosignerGRPCGetNoncesResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cosigner_service_shamir_proto_init() }
func file_cosigner_service_shamir_proto_init() {
	if File_cosigner_service_shamir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosigner_service_shamir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nonce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosigner_service_shamir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HRST); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosigner_service_shamir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCSetNoncesAndSignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosigner_service_shamir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCSetNoncesAndSignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosigner_service_shamir_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCGetNoncesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosigner_service_shamir_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosignerGRPCGetNoncesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosigner_service_shamir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cosigner_service_shamir_proto_goTypes,
		DependencyIndexes: file_cosigner_service_shamir_proto_depIdxs,
		MessageInfos:      file_cosigner_service_shamir_proto_msgTypes,
	}.Build()
	File_cosigner_service_shamir_proto = out.File
	file_cosigner_service_shamir_proto_rawDesc = nil
	file_cosigner_service_shamir_proto_goTypes = nil
	file_cosigner_service_shamir_proto_depIdxs = nil
}
